version: '3.8'

services:
  # PHP-FPM Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nyuwi-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./storage:/var/www/storage
    networks:
      - nyuwi-network
    depends_on:
      - db

  # Nginx Service
  webserver:
    image: nginx:alpine
    container_name: nyuwi-webserver
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - nyuwi-network
    depends_on:
      - app

  # MySQL Service
  db:
    image: mysql:8.0
    container_name: nyuwi-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: nyuwicreation
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: password
      MYSQL_USER: nyuwi
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - nyuwi-network

  # Redis Service (optional, for caching)
  redis:
    image: redis:alpine
    container_name: nyuwi-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - nyuwi-network

networks:
  nyuwi-network:
    driver: bridge

volumes:
  db_data:
    driver: local